### ISSUE TITLE
Multiplying drop with butchery

### ISSUE THREAD

**Issue by thornss** [LeandroTheDev/level_up#1]
Multipliers need tweaking. 
With Butchery mod drops from butchery hooks and tables skyrocket. After killing one bear and butchering it with cutlery 5 I have 30 large raw hides, quite a bit of fat, 7 brains, 15 sinews and 179 bushmeat (179 in one slot).
No problems with bones as you collect them from carcasses.

**Comment by LeandroTheDev** [comment]
The mod is using the base multiply 1.0 but the default is 0.5, already changed and fixed in 1.0.6
also fixed for ore drops too

**Comment by thornss** [comment]
Same issue after updating to 1.0.9
Everything was fine up until 1.0.8 and now again some fantastical numbers on a butchering. Almost 200 feathers and 16 poultry, that's just one rooster
one wolf - ~16 bushmeat, ~12 raw hides and several lumps cof fat
![Screenshot_3](https://github.com/LeandroTheDev/level_up/assets/55922862/17475bfe-f5b1-46fa-b6f4-2e4d57e4eecc)

**Comment by LeandroTheDev** [comment]
Check the configuration "knifeBaseHarvestMultiply" in levelup/assets/levelup/config/levelstats/knife.json, the default is 0.5, if is 1.0 or more is multiplying by 2 or more the loots

**Comment by thornss** [comment]
"knifeBaseHarvestMultiply": 0.5,

**Comment by LeandroTheDev** [comment]
i will make any extended log to know what happens in your game, i am really confused because in my game single player and server is working properly

**Comment by thornss** [comment]
![Screenshot_4](https://github.com/LeandroTheDev/level_up/assets/55922862/a24537c1-071f-475c-84ac-0b73bc24069a)

**Comment by thornss** [comment]
and that is one wolf )

**Comment by LeandroTheDev** [comment]
Thanks for report, finally found whats the problem, forget to remove some ``=`` in the multiply code
```baseMultiply += baseMultiply *= multiply;``` => ```baseMultiply += baseMultiply * multiply;```.
This error is also in some others calculations like ore drop and mining speed, already fixed in version 1.1.1.

**Comment by thornss** [comment]
thanks, great )
