### ISSUE TITLE
Starvation not doing damage.

### ISSUE THREAD

**Issue by gerpyy** [LeandroTheDev/level_up#10]
**The bug**
I do not take damage from starvation when continuing a saved world. However other players who join me over LAN do still die of starvation. When I remove this mod I take damage as normal. If I kill myself I also take damage again until I load the world again.

**Logs with enableExtendedLog**
[server-main.txt](https://github.com/LeandroTheDev/level_up/files/15211328/server-main.txt)
[client-main.txt](https://github.com/LeandroTheDev/level_up/files/15211329/client-main.txt)

**Singleplayer or Server?**
I experience it in both singleplayer and when I host over LAN

.

**Comment by LeandroTheDev** [comment]
Thanks JoeAyyas and gerpyy, this probably happens because the damage from leather armor is not percentage, it is unique, and your level probably already covers the damage from hunger, this clearly shouldn't work like that and I'm already working to correct it

**Comment by LeandroTheDev** [comment]
Fixed in full release of 1.1.8
