### ISSUE TITLE
Compat error with ACulinaryArtillery

### ISSUE THREAD

**Issue by Vane79** [LeandroTheDev/level_up#12]
**The bug**
Putting water into the saucepan leads to Level Up thinking food's done and trying to award xp multiple times per tick, thus throttling the processor. Although the firepit is cold and the saucepan didn't make any recipe.

A Culinary Artillery version v1.1.4 
LevelUp version v1.1.8-pre.2

![изображение](https://github.com/LeandroTheDev/level_up/assets/36656584/f7e7eda5-062e-41d6-b7ef-cdac1ce99c32)

**Logs**
This happens to the point of server crash. Client-side log.

7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:40 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623
7.5.2024 21:24:41 [Notification] [LevelUP] aculinaryartillery:saucepan-burned finished cooking, X: 511868, Y: 114, Z: 511623

**Singleplayer/LAN/Multiplayer?**
Both singleplayer and lan

**Comment by LeandroTheDev** [comment]
Thank you for the report.
Add the aculinaryartillery:saucepan-burned to the cookingpots.json in /assets/levelup/config/levelstats/cookingpots.json, normally the cpu overflow will not happen, but i missed something in the code for preventing that, will be fixed in next update
```json
{
  "game:claypot-cooked": 3.0,
  "aculinaryartillery:saucepan-burned": 3.0
}
```

Also when you cook something that doesn't belong to vanilla, in your client log file theres something about  "[LevelUP] Cooking output: ..." with the output you can add it to cookingpots.json too, unfortunately for third party mods, if you want to gain experience cooking with the new recipes you need to manually add the settings.

**Comment by Vane79** [comment]
That fixes the saucepan, but the problem is that a culinary artillery also has small and large cauldrons with different metals. Those break with water in the cold firepit as well. It's just for the record, for anybody who comes into this issue - cauldrons are essentially saucepans.
