### ISSUE TITLE
Harvest Compatibility 

### ISSUE THREAD

**Issue by lmbz115** [LeandroTheDev/level_up#22]
**The bug**
LevelUp isn’t correctly calculating harvest drops based on compatibility with other mods. 

How to recreate:
Fresh install of level_up v1.2.5
Fresh install of rpg difficulty v1.0.7 (I use this mod because it is referenced as an example in the levelup wiki) - modify 
Clear vintagestorydata cache folder
Start single player world 

Kill something at 0,0 (both mods are indeed working because skills level up and mob health is varied) 

Teleport to 10000, 10000, spawn mob, kill and harvest it to get same amount of loot from 0,0. 

**Singleplayer/LAN/Multiplayer?**
Occurs in both single player and multiplayer. 

**
I used fresh installs of both mods to understand the harmony compatibility patch. I am unsure of where the issue actually lies, having rpg difficulty alone in the mod folder works as intended for loots, but when level up is added loots are base. To be fair I can’t quite tell if level up is even modifying the level up harvest multiplier as in my play through I haven’t noticed excessive loot amounts.

**Comment by LeandroTheDev** [comment]
I have tested in the last version from LevelUP and RPGDifficulty
killing any rooster in 10000 120 10000, give me the values of 0,81 for the level and 3.8 for the distance multipliyer, resulting in any loot increase of 4.62 in total
``[LevelUP] BoboDev harvested any entity with knife, multiply drop: 4.62, values: 0.81999993 + 3.8``

Tested in 0 120 0
``[LevelUP] BoboDev harvested any entity with knife, multiply drop: 0.78, values: 0.78 + 0``
Another test after tp in 10000 120 10000
``[LevelUP] BoboDev harvested any entity with knife, multiply drop: 0.81999993, values: 0.81999993 + 0``

Final test in 10000 120 10000
``[LevelUP] BoboDev harvested any entity with knife, multiply drop: 4.66, values: 0.85999995 + 3.8``

The numbers is ok in the tests, i will compile a special version with this debug lines, so you can test it and provide me the logs so i can check what is happening

The left number is the multiply by level, the right number is the multiply of distance/height/age

[levelup_1.2.9-pre.1.zip](https://github.com/user-attachments/files/17177237/levelup_1.2.9-pre.1.zip)
