### ISSUE TITLE
Meal issue

### ISSUE THREAD

**Issue by Neko-Yukari** [LeandroTheDev/level_up#5]
**The bug**
When i play this mod with xskill,which is also an skill-like mod but in talent points(at that time i just have a talent that extend shelf time for 10%).And i was cooking a regular meal with redmeat and berries. When the meal was coming to finish, the CPU usage sunddenly come to 100% with stiff mouse movement.This continues before i open the cooking pot, and there is about 42 dish in the cooking bot with shelf life that require scientific notation(like 2E20 years and it's still rising) 

**Logs with enableExtendedLog**
The game either crash without log or just keep running

**Singleplayer or Server?**
In singleplayer

**Comment by LeandroTheDev** [comment]
> I meet same problem. Installed xskill too, and then a rabbit will drop tones of meat and fur. I tried to set all level to zero or turn off those two mods but it doesn't fix it. Seems it broke the save permanently. Is there any other way to fix it ?

Whats the first version of level up mod do you added in your world? older versions rewrited the harvest drops, if that is the case unfortunately i can't help you, but if you want to research how to solve it you can try searching for how to change the values ​​of "animalLootDropRate", using the last version of level up this is not a problem.



> **The bug** When i play this mod with xskill,which is also an skill-like mod but in talent points(at that time i just have a talent that extend shelf time for 10%).And i was cooking a regular meal with redmeat and berries. When the meal was coming to finish, the CPU usage sunddenly come to 100% with stiff mouse movement.This continues before i open the cooking pot, and there is about 42 dish in the cooking bot with shelf life that require scientific notation(like 2E20 years and it's still rising)
> 
> **Logs with enableExtendedLog** The game either crash without log or just keep running
> 
> **Singleplayer or Server?** In singleplayer

You can find the logs in ``C:\Users\username\AppData\Roaming\VintagestoryData\Logs`` i need the client-main and server-main, i need you to do the exactly same error and send me the logs after causing the errors

**Comment by LeandroTheDev** [comment]
I think this error is caused from the version 1.1.3 and already has a reported in this [issue](https://github.com/LeandroTheDev/level_up/issues/4), also is fixed in the lastest version, so i am closing this issue, if this issue persist in the newest version feel free to re open
