### ISSUE TITLE
Infinite shield

### ISSUE THREAD

**Issue by Shadeloid** [LeandroTheDev/level_up#6]
**The bug**
When enemies hit the shield, it doesn't reproduce sound nor does it lower the durability of the shield, so basically infinite shield

**Logs with enableExtendedLog**

[client-main.txt](https://github.com/LeandroTheDev/level_up/files/15097527/client-main.txt)
[server-main.txt](https://github.com/LeandroTheDev/level_up/files/15097529/server-main.txt)

**Singleplayer or Server?**
Single player

**Comment by LeandroTheDev** [comment]
Thanks for the report, I forgot to make a singleplayer treatment for the shield not lose durability mechanic, it will be fixed in version 1.1.7

before:
```css
if(instance.serverAPI != null)
```

after
```css
if(instance.serverAPI != null || (instance.clientAPI != null && instance.clientAPI.api.IsSinglePlayer))
```
