### ISSUE TITLE
Infinite shield still persists

### ISSUE THREAD

**Issue by Shadeloid** [LeandroTheDev/level_up#7]
**The bug**
So supposedly the new update fixes the shield not losing durability bug. But it looks like it's still the same. I disabled solid shields mod for confliction, and still nothing. I don't know what's causing it.

**Logs with enableExtendedLog**

[server-main.txt](https://github.com/LeandroTheDev/level_up/files/15123549/server-main.txt)
[client-main.txt](https://github.com/LeandroTheDev/level_up/files/15123550/client-main.txt)

**Singleplayer or Server?**
Single player

**Comment by LeandroTheDev** [comment]
Fixed in 1.1.7-1

Theres a lot of problems in the native code from shield protection, which became apparent after I made single player compatibility

**Comment by LeandroTheDev** [comment]
[Original issue](https://github.com/LeandroTheDev/level_up/issues/6)
