### ISSUE TITLE
helve hammer 

### ISSUE THREAD

**Issue by ockey022** [LeandroTheDev/level_up#8]
I'm not sure if its a bug but after several iron blooms finished every next is doubled, tripled and quadrupled but the thing is that I'm getting it just 2 3 or 4 ingots from one bloom after several blooms I get like 64 216 512 ect. and after its finished it doesn't finish it bloom stays like ingot then i need to pick it up and place it on anvil again to get ingots from bloom, 
I'm getting that in singleplayer

**Comment by LeandroTheDev** [comment]
Yes this is definitely a bug, the correct way is to double the current recipe output quantity, but actually is duplicating the actual amount you have in inventory, i will fix that

**Comment by LeandroTheDev** [comment]
Fixed in 1.1.8
