### ISSUE TITLE
LAN leveling

### ISSUE THREAD

**Issue by Mars327** [LeandroTheDev/level_up#9]
This is a LAN game/ nondedicated

My buddy and I are using the mod and both our actions are only leveling me (the host). The only levels that he is able to increase is some of the combat skills like bow and knife, but even then I am leveling up those skills while not partaking in said activities. 

I'm not sure what logs would be useful since its not throwing errors just seems to be working not as intended.

(Also the mod doesn't like being uninstalled causes harvesting of absurd amounts of meat and such and me retaining my incredibly high health)

**Comment by LeandroTheDev** [comment]
This will take some time to fix, but actually you can simple disable all levels in mod config base.json, also you can use the command /levelup changeexperience YourName Level 0, to reset your levels to not have the buffs

**Comment by LeandroTheDev** [comment]
I cannot test it by myself, but i think is actually fixed in the 1.1.8a2

the singleplayer channel is now receiving the player lan name and giving experience to it

if not fixed feel free to reopen this issue

**Comment by Vane79** [comment]
Cannot attest to lan exp being fixed, but the removal of the mod borks the world, as [Mars327](https://github.com/Mars327) said.
A single rabbit drops 50+ meat. Can you do something with that?
